spring.application.name=Hiring

#Database
spring.datasource.driver-class-name=${Db_driver}
spring.datasource.username=${Db_User}
spring.datasource.password=${Db_password}
spring.datasource.url=${DB_url}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update



#ai
spring.ai.openai.api-key=${ai_key}
spring.ai.openai.chat.model=${ai_model}


#mail
spring.mail.host=${host}
spring.mail.port=${port}
spring.mail.username=${username}
spring.mail.password=${password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
email.from=${from}

